#!/usr/bin/env bash
#
# Fit and interpret Gaussian hidden Markov models for zoospore trajectories.
#
# Usage:
#   ./fit_hidden_markov_models.sh CONFIG_FILE
#
# The Python interpreter is read from python.conf, generated by
# setup_python.sh. HMM parameters are read from CONFIG_FILE.
#

set -Eeuo pipefail

cd "$(dirname "$0")"

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

usage() {
    cat <<EOF
Usage:
  $(basename "$0") CONFIG_FILE

CONFIG_FILE is a trusted Bash configuration file containing the input/output
paths and HMM fitting parameters.
EOF
}

if (( $# != 1 )); then
    usage >&2
    exit 1
fi

case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
esac

PYTHON_CONFIG="python.conf"
ANALYSIS_CONFIG="$1"
PYTHON_SCRIPT="fit_and_interpret_zoospore_hmm.py"

[[ -f "$PYTHON_CONFIG" ]] \
    || die "Python configuration file not found: $PYTHON_CONFIG"

[[ -f "$ANALYSIS_CONFIG" ]] \
    || die "HMM configuration file not found: $ANALYSIS_CONFIG"

[[ -f "$PYTHON_SCRIPT" ]] \
    || die "Python script not found: $PYTHON_SCRIPT"

# shellcheck disable=SC1090
source "$PYTHON_CONFIG"

# shellcheck disable=SC1090
source "$ANALYSIS_CONFIG"

: "${PYTHON:?PYTHON is not defined in $PYTHON_CONFIG}"
: "${METRICS_DIR:?METRICS_DIR is not defined in $ANALYSIS_CONFIG}"

[[ -x "$PYTHON" ]] \
    || die "Python interpreter is not executable: $PYTHON"

[[ -d "$METRICS_DIR" ]] \
    || die "Metrics directory not found: $METRICS_DIR"

if [[ ! -f "$METRICS_DIR/step_metrics.csv" \
   && ! -f "$METRICS_DIR/step_metrics.tsv" ]]; then
    die "Neither step_metrics.csv nor step_metrics.tsv was found in $METRICS_DIR"
fi

if [[ ! -f "$METRICS_DIR/turn_metrics.csv" \
   && ! -f "$METRICS_DIR/turn_metrics.tsv" ]]; then
    die "Neither turn_metrics.csv nor turn_metrics.tsv was found in $METRICS_DIR"
fi

HMM_ANALYSIS_DIR="${HMM_ANALYSIS_DIR:-$METRICS_DIR/hmm_analysis}"

DT="${DT:-0.22}"
MIN_STATES="${MIN_STATES:-2}"
MAX_STATES="${MAX_STATES:-7}"
INITIALIZATIONS="${INITIALIZATIONS:-10}"
N_ITER="${N_ITER:-500}"
TOL="${TOL:-1e-4}"
COVARIANCE_TYPE="${COVARIANCE_TYPE:-diag}"
MIN_TRACK_OBSERVATIONS="${MIN_TRACK_OBSERVATIONS:-10}"
ACCELERATION_SCALE="${ACCELERATION_SCALE:-100}"
TRANSITION_GRAPH_THRESHOLD="${TRANSITION_GRAPH_THRESHOLD:-0.02}"
CONNECTIVITY_THRESHOLD="${CONNECTIVITY_THRESHOLD:-0.02}"
MINIMUM_STATE_OCCUPANCY="${MINIMUM_STATE_OCCUPANCY:-0.01}"
MINIMUM_STATE_POSTERIOR="${MINIMUM_STATE_POSTERIOR:-0.50}"
MAX_TRACKS_PLOT="${MAX_TRACKS_PLOT:-200}"
QUANTILE_COUNT="${QUANTILE_COUNT:-1001}"
DPI="${DPI:-300}"
WRITE_DECODED_ALL="${WRITE_DECODED_ALL:-0}"

mkdir -p "$HMM_ANALYSIS_DIR"

args=(
    "$METRICS_DIR"
    --outdir "$HMM_ANALYSIS_DIR"
    --dt "$DT"
    --min-states "$MIN_STATES"
    --max-states "$MAX_STATES"
    --initializations "$INITIALIZATIONS"
    --n-iter "$N_ITER"
    --tol "$TOL"
    --covariance-type "$COVARIANCE_TYPE"
    --min-track-observations "$MIN_TRACK_OBSERVATIONS"
    --acceleration-scale "$ACCELERATION_SCALE"
    --transition-graph-threshold "$TRANSITION_GRAPH_THRESHOLD"
    --connectivity-threshold "$CONNECTIVITY_THRESHOLD"
    --minimum-state-occupancy "$MINIMUM_STATE_OCCUPANCY"
    --minimum-state-posterior "$MINIMUM_STATE_POSTERIOR"
    --max-tracks-plot "$MAX_TRACKS_PLOT"
    --quantile-count "$QUANTILE_COUNT"
    --dpi "$DPI"
)

case "${WRITE_DECODED_ALL,,}" in
    1|true|yes|on)
        args+=(--write-decoded-all)
        ;;
    0|false|no|off|"")
        ;;
    *)
        die "WRITE_DECODED_ALL must be 0/1, true/false, yes/no, or on/off"
        ;;
esac

echo "Fitting and interpreting zoospore HMMs..."
echo "  Metrics:                    $METRICS_DIR"
echo "  Output:                     $HMM_ANALYSIS_DIR"
echo "  Time step:                  $DT s"
echo "  State range:                $MIN_STATES-$MAX_STATES"
echo "  Initializations per model:  $INITIALIZATIONS"
echo "  Maximum EM iterations:      $N_ITER"
echo "  Convergence tolerance:      $TOL"
echo "  Covariance type:            $COVARIANCE_TYPE"
echo "  Minimum track observations: $MIN_TRACK_OBSERVATIONS"
echo "  Acceleration scale:         $ACCELERATION_SCALE"
echo "  Connectivity threshold:     $CONNECTIVITY_THRESHOLD"
echo "  Minimum state occupancy:    $MINIMUM_STATE_OCCUPANCY"
echo "  Minimum state posterior:    $MINIMUM_STATE_POSTERIOR"
echo "  Quantiles per state:        $QUANTILE_COUNT"
echo "  Write all decoded tables:   $WRITE_DECODED_ALL"
echo "  Python:                     $PYTHON"

"$PYTHON" "$PYTHON_SCRIPT" "${args[@]}"

echo "HMM fitting and interpretation completed."
