#!/usr/bin/env bash

set -Eeuo pipefail

PYTHON_COMMAND="${1:-/usr/bin/env python3}"
VENV_DIR="python_venv"
CONFIG_FILE="python.conf"

# -----------------------------------------------------------------------------
# Create the virtual environment
# -----------------------------------------------------------------------------

read -r -a SYSTEM_PYTHON <<< "$PYTHON_COMMAND"

if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    echo "Creating Python virtual environment..."
    "${SYSTEM_PYTHON[@]}" -m venv "$VENV_DIR"
fi

PYTHON="$VENV_DIR/bin/python"

echo "Upgrading pip..."
"$PYTHON" -m pip install --quiet --upgrade pip

echo "Installing required packages..."
"$PYTHON" -m pip install --quiet --upgrade \
    numpy \
    pandas \
    scipy \
    matplotlib \
    scikit-learn \
    hmmlearn \
    tol-colors

# -----------------------------------------------------------------------------
# Write configuration
# -----------------------------------------------------------------------------

cat > "$CONFIG_FILE" <<EOF
# Automatically generated by setup_python.sh

PYTHON="$(cd "$VENV_DIR/bin" && pwd -P)/python"
EOF

echo
echo "Python successfully configured."
echo "Configuration written to: $CONFIG_FILE"
echo "Python interpreter:       $PYTHON"
